#! /bin/sh

set -e

versions="3.6 3.7 3.8"

case "$1" in
  configure)
    for v in $versions; do
      python=python$v
      [ -x /usr/bin/$python ] || continue
      files=$(dpkg -L python3-lib2to3 | sed -n '/^\/usr\/lib\/'$python'\/.*\.py$/p')
      if [ -n "$files" ]; then
	/usr/bin/$python -E -S /usr/lib/$python/py_compile.py $files
	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
	  /usr/bin/$python -E -S -O /usr/lib/$python/py_compile.py $files
	fi
      else
	echo >&2 "$python: can't get files for byte-compilation"
      fi
    done
esac



exit 0
